{{- if not (lookup "v1" "Secret" .Release.Namespace "oracle-nosql-props-secret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: oracle-nosql-props-secret
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  endpoint: ""
  tenant: ""
  user: ""
  fingerprint: ""
  ORACLE_CLOUD_COMPARTMENT_ID: ""
  ORACLE_CLOUD_TENANT_ID: ""
  ORACLE_CLOUD_USER_ID: ""
  ORACLE_CLOUD_FINGERPRINT: ""
# TODO: deprecate old fields
{{- end -}}
---
{{- if not (lookup "v1" "Secret" .Release.Namespace "oracle-nosql-key-secret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: oracle-nosql-key-secret
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  cert.pem: ""
{{- end -}}
