{{- if not (lookup "v1" "Secret" .Release.Namespace "oracle-email-props") -}}
apiVersion: v1
kind: Secret
metadata:
  name: oracle-email-props
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  EMAIL_USER: ""
  EMAIL_PASSWORD: ""
{{- end -}}
