{{- if not (lookup "v1" "Secret" .Release.Namespace "jwt-key") -}}
apiVersion: v1
kind: Secret
metadata:
  name: jwt-key
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  JWT_GENERATOR_SIGNATURE_SECRET: {{ (randAlphaNum 32 | b64enc) }}
{{- end -}}
