apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: non-prod-critical
value: {{ .Values.priorities.nonProdCritical }}
preemptionPolicy: Never
globalDefault: false
description: "Used for critical non-prod workloads"