apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: prod-critical
value: {{ .Values.priorities.prodCritical }}
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "Used for critical prod workloads"