{{- if not (lookup "v1" "Secret" .Release.Namespace "oracle-nosql-props-secret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: oracle-nosql-props-secret
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  endpoint: ""
  tenant: ""
  user: ""
  fingerprint: ""
#  endpoint: {{ .Values.connectionProps.endpoint | b64enc | quote }}
#  tenant: {{ .Values.connectionProps.tenant | b64enc | quote }}
#  user: {{ .Values.connectionProps.user | b64enc | quote }}
#  fingerprint: {{ .Values.connectionProps.fingerprint | b64enc | quote }}
{{- end -}}
---
{{- if not (lookup "v1" "Secret" .Release.Namespace "oracle-nosql-key-secret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: oracle-nosql-key-secret
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
#  cert.pem: {{ .Values.connectionProps.key | b64enc | quote }}
  cert.pem: ""
{{- end -}}
