{{- $fullName := include "xivgear-beta.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xivgear-beta.fullname" . }}
  labels:
    {{- include "xivgear-beta.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "xivgear-beta.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xivgear-beta.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      priorityClassName: {{ .Values.priorityClassName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xivgear-beta.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
{{- if .Values.preview.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xivgear-beta.preview-fullname" . }}
  labels:
    {{- include "xivgear-beta.previewLabels" . | nindent 4 }}
  {{- with ( coalesce .Values.preview.deploymentAnnotations .Values.deploymentAnnotations ) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.preview.revisionHistoryLimit }}
  {{- if not .Values.preview.autoscaling.enabled }}
  replicas: {{ .Values.preview.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "xivgear-beta.previewSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xivgear-beta.previewLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      priorityClassName: {{ .Values.preview.priorityClassName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xivgear-beta.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-preview-injector
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.preview.image.repository | default .Values.image.repository }}:{{ coalesce .Values.preview.image.tag .Values.image.tag .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.preview.image.pullPolicy | default .Values.image.pullPolicy }}
          env:
            - name: 'IS_PREVIEW_SERVER'
              value: 'true'
            {{- if .Values.preview.shortlinkOverride }}
            - name: 'SHORTLINK_SERVER'
              value: {{ .Values.preview.shortlinkOverride }}
            {{- end }}
            - name: 'FRONTEND_SERVER'
              value: {{ .Values.preview.frontendServerOverride | default (printf "http://%s:%s/" $fullName ( toString $.Values.service.port ) ) }}
            {{- with (first .Values.ingress.hosts) }}
            - name: 'FRONTEND_CLIENT'
              value: {{ $.Values.preview.frontendClientOverride | default (printf "https://%s/" .host ) }}
            {{- end }}
            {{- if .Values.preview.extraScripts }}
            - name: 'EXTRA_SCRIPTS'
              value: {{ $.Values.preview.extraScripts }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.preview.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          resources:
            {{- toYaml .Values.preview.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}