apiVersion: v1
kind: Service
metadata:
  name: {{ include "xivgear-beta.fullname" . }}
  labels:
    {{- include "xivgear-beta.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "xivgear-beta.selectorLabels" . | nindent 4 }}
---
{{- if .Values.preview.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xivgear-beta.preview-fullname" . }}
  labels:
    {{- include "xivgear-beta.previewLabels" . | nindent 4 }}
spec:
  type: {{ .Values.preview.service.type }}
  ports:
    - port: {{ .Values.preview.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "xivgear-beta.previewSelectorLabels" . | nindent 4 }}
{{- end }}