xivgear-static:

  deploymentAnnotations: &deployAnn
    keel.sh/policy: "force"
    keel.sh/trigger: "poll"
    keel.sh/pollSchedule: "@every 2m"


  replicaCount: 2

  image:
    repository: ghcr.io/xiv-gear-planner/xivgear-static
    pullPolicy: Always
    tag: "prod"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
#      nginx.ingress.kubernetes.io/rewrite-target: /$1
    hosts:
      - host: &tophost 'hbeta.xivgear.app'
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: &wwwhost 'www.hbeta.xivgear.app'
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: &tlsconfig
      - secretName: letsencrypt-production
        hosts:
          - *tophost
          - *wwwhost

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

xivgear-storage-api:

  deploymentAnnotations: *deployAnn

  replicaCount: 2

  image:
    repository: ghcr.io/xiv-gear-planner/gear-planner-server
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "master"

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Automatically mount a ServiceAccount's API credentials?
    automount: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: &apihost 'api.hbeta.xivgear.app'
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
      - host: &sharehost 'share.hbeta.xivgear.app'
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
    tls:
      - secretName: letsencrypt-production
        hosts:
          - *apihost
          - *sharehost

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

