# This file creates the secret objects if they do not exist, but you will need to
  # edit them manually in kubectl to actually fill in the values so that
{{- if not (lookup "v1" "Secret" .Release.Namespace "oracle-objectstorage-secret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: oracle-objectstorage-secret
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  ORACLE_CLOUD_OBJECT_STORAGE_NAMESPACE: ""
  ORACLE_CLOUD_OBJECT_STORAGE_REGION: ""
  ORACLE_CLOUD_COMPARTMENT_ID: ""
  ORACLE_CLOUD_TENANT_ID: ""
  ORACLE_CLOUD_USER_ID: ""
  ORACLE_CLOUD_FINGERPRINT: ""
{{- end -}}
---
{{- if not (lookup "v1" "Secret" .Release.Namespace "oracle-objectstorage-key-secret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: oracle-objectstorage-key-secret
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  cert.pem: ""
{{- end -}}
